"""
Django settings for school_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# --- Base Directory ---
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Initialize environ and read .env ---
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# --- Security ---
SECRET_KEY = env('SECRET_KEY', default='django-insecure-nd)gw=sc=%-w2a8wxg0)&rs0f!u7_^wn^a40@(w%eoe((-&r^h')

# Debug and Allowed Hosts
DEBUG = env.bool('DEBUG', default=False)
ALLOWED_HOSTS = ["*"]

# --- Installed Apps ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',             # your main app
    'crispy_forms',     # optional, for better forms
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',          # ✅ Must be first
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',       # ✅ Must be after sessions
    'django.contrib.messages.middleware.MessageMiddleware',          # ✅ Required for admin
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # ✅ Must be exactly this
        'DIRS': [BASE_DIR / 'templates'],  # Optional: your custom templates folder
        'APP_DIRS': True,                   # ✅ Enables templates inside app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # ✅ Required by admin
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

# --- Database (MySQL) ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME', default='school_db'),
        'USER': env('DB_USER', default='root'),
        'PASSWORD': env('DB_PASSWORD', default='1234m'),
        'HOST': env('DB_HOST', default='127.0.0.1'),
        'PORT': env('DB_PORT', default='3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}
# settings.py

ROOT_URLCONF = 'school_project.urls'

# --- Authentication ---
AUTH_USER_MODEL = 'core.User'
# settings.py
LOGIN_URL = '/login/'           # URL for login page
LOGIN_REDIRECT_URL = '/'        # Redirect after login
LOGOUT_REDIRECT_URL = '/login/' # Redirect after logout

# --- Localization ---
TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True

# --- Static & Media ---
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
